AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smartman API Development and Testing Tool (Complete Project)

Parameters:
    SupabaseJwtSecret:
        Type: String
        Description: Supabase JWT secret for authentication
        NoEcho: true
    AllowedOrigin:
        Type: String
        Description: CORS allowed origin
        Default: '*'
    DeepSeekApiKey:
        Type: String
        Description: DeepSeek API key
        NoEcho: true
    UpstashRedisRestUrl:
        Type: String
        Description: Upstash Redis REST API URL
        NoEcho: true
    UpstashRedisRestToken:
        Type: String
        Description: Upstash Redis REST API Token
        NoEcho: true

Resources:
    SmartmanTable:
        Type: AWS::DynamoDB::Table
        DeletionPolicy: Retain
        Properties:
            TableName: !Sub 'Smartman-${AWS::StackName}'
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: PK
                  AttributeType: S
                - AttributeName: SK
                  AttributeType: S
            KeySchema:
                - AttributeName: PK
                  KeyType: HASH
                - AttributeName: SK
                  KeyType: RANGE

    SmartmanBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub 'smartman-${AWS::StackName}-${AWS::AccountId}'
            AccessControl: Private
            PublicAccessBlockConfiguration:
                BlockPublicAcls: true
                BlockPublicPolicy: true
                IgnorePublicAcls: true
                RestrictPublicBuckets: true

    RestApiRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: apigateway.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName: InvokeLambdaPolicy
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action: lambda:InvokeFunction
                            Resource:
                                - !GetAtt AuthModuleResources.Outputs.GetProfileFunctionArn
                                - !GetAtt AuthModuleResources.Outputs.UpdateProfileFunctionArn
                                - !GetAtt CollectionsModuleResources.Outputs.SaveCollectionFunctionArn
                                - !GetAtt CollectionsModuleResources.Outputs.ListCollectionsFunctionArn
                                - !GetAtt CollectionsModuleResources.Outputs.DeleteCollectionFunctionArn
                                - !GetAtt ErrorExplanationModuleResources.Outputs.ExplainErrorFunctionArn
                                - !GetAtt DocumentationModuleResources.Outputs.GenerateDocsFunctionArn
                                - !GetAtt RequestModuleResources.Outputs.ExecuteRequestFunctionArn
                - PolicyName: S3AccessPolicy
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action:
                                - s3:PutObject
                                - s3:GetObject
                                - s3:PutObjectAcl
                            Resource: !Sub 'arn:aws:s3:::smartman-${AWS::StackName}-${AWS::AccountId}/*'

    SmartmanApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            DefinitionBody:
                Fn::Transform:
                    Name: AWS::Include
                    Parameters:
                        Location: ./api/backend-api.yaml
            Cors:
                AllowMethods: "'GET,POST,OPTIONS,DELETE'"
                AllowHeaders: "'Content-Type,Authorization'"
                AllowOrigin: !Ref AllowedOrigin

    AuthModuleResources:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./modules/auth/template.yaml
            Parameters:
                TableName: !Ref SmartmanTable
                SupabaseJwtSecret: !Ref SupabaseJwtSecret
                AllowedOrigin: !Ref AllowedOrigin

    CollectionsModuleResources:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./modules/collections/template.yaml
            Parameters:
                TableName: !Ref SmartmanTable
                SupabaseJwtSecret: !Ref SupabaseJwtSecret
                AllowedOrigin: !Ref AllowedOrigin
                UpstashRedisRestUrl: !Ref UpstashRedisRestUrl
                UpstashRedisRestToken: !Ref UpstashRedisRestToken

    ErrorExplanationModuleResources:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./modules/error-explanation/template.yaml
            Parameters:
                TableName: !Ref SmartmanTable
                SupabaseJwtSecret: !Ref SupabaseJwtSecret
                AllowedOrigin: !Ref AllowedOrigin
                DeepSeekApiKey: !Ref DeepSeekApiKey
                UpstashRedisRestUrl: !Ref UpstashRedisRestUrl
                UpstashRedisRestToken: !Ref UpstashRedisRestToken

    DocumentationModuleResources:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./modules/documentation/template.yaml
            Parameters:
                TableName: !Ref SmartmanTable
                SupabaseJwtSecret: !Ref SupabaseJwtSecret
                AllowedOrigin: !Ref AllowedOrigin
                BucketName: !Ref SmartmanBucket

    RequestModuleResources:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./modules/request/template.yaml
            Parameters:
                TableName: !Ref SmartmanTable
                SupabaseJwtSecret: !Ref SupabaseJwtSecret
                AllowedOrigin: !Ref AllowedOrigin
                UpstashRedisRestUrl: !Ref UpstashRedisRestUrl
                UpstashRedisRestToken: !Ref UpstashRedisRestToken

Outputs:
    SmartmanApi:
        Description: URL of the API Gateway
        Value: !Sub 'https://${SmartmanApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    GetProfileFunctionArn:
        Description: ARN of the GetProfile Lambda Function
        Value: !GetAtt AuthModuleResources.Outputs.GetProfileFunctionArn
    UpdateProfileFunctionArn:
        Description: ARN of the UpdateProfile Lambda Function
        Value: !GetAtt AuthModuleResources.Outputs.UpdateProfileFunctionArn
    SaveCollectionFunctionArn:
        Description: ARN of the SaveCollection Lambda Function
        Value: !GetAtt CollectionsModuleResources.Outputs.SaveCollectionFunctionArn
    ListCollectionsFunctionArn:
        Description: ARN of the ListCollections Lambda Function
        Value: !GetAtt CollectionsModuleResources.Outputs.ListCollectionsFunctionArn
    DeleteCollectionFunctionArn:
        Description: ARN of the DeleteCollection Lambda Function
        Value: !GetAtt CollectionsModuleResources.Outputs.DeleteCollectionFunctionArn
    ExplainErrorFunctionArn:
        Description: ARN of the ExplainError Lambda Function
        Value: !GetAtt ErrorExplanationModuleResources.Outputs.ExplainErrorFunctionArn
    GenerateDocsFunctionArn:
        Description: ARN of the GenerateDocs Lambda Function
        Value: !GetAtt DocumentationModuleResources.Outputs.GenerateDocsFunctionArn
    ExecuteRequestFunctionArn:
        Description: ARN of the ExecuteRequest Lambda Function
        Value: !GetAtt RequestModuleResources.Outputs.ExecuteRequestFunctionArn
