AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smartman API Development and Testing Tool

Parameters:
    SupabaseJwtSecret:
        Type: String
        Description: Supabase JWT secret for authentication
    DeepSeekApiKey:
        Type: String
        Description: DeepSeek API key for LLM
    UpstashRedisUrl:
        Type: String
        Description: Upstash Redis connection URL
    AllowedOrigin:
        Type: String
        Description: CORS allowed origin
        Default: '*'

Resources:
    SmartmanTable:
        Type: AWS::DynamoDB::Table
        DeletionPolicy: Retain
        Properties:
            TableName: !Sub 'Smartman-${AWS::StackName}'
            BillingMode: PAY_PER_REQUEST
            AttributeDefinitions:
                - AttributeName: PK
                  AttributeType: S
                - AttributeName: SK
                  AttributeType: S
            KeySchema:
                - AttributeName: PK
                  KeyType: HASH
                - AttributeName: SK
                  KeyType: RANGE

    DocsBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Sub 'smartman-docs-${AWS::StackName}'

    RestApiRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                    - Effect: Allow
                      Principal:
                          Service: apigateway.amazonaws.com
                      Action: sts:AssumeRole
            Policies:
                - PolicyName: InvokeLambdaPolicy
                  PolicyDocument:
                      Version: '2012-10-17'
                      Statement:
                          - Effect: Allow
                            Action: lambda:InvokeFunction
                            Resource:
                                - !GetAtt AuthModuleResources.Outputs.GetProfileFunctionArn
                                - !GetAtt AuthModuleResources.Outputs.UpdateProfileFunctionArn
                                # Add other module ARNs when implemented
                                # - !GetAtt RequestModuleResources.Outputs.ExecuteRequestFunctionArn
                                # - !GetAtt CollectionsModuleResources.Outputs.SaveCollectionFunctionArn
                                # - !GetAtt CollectionsModuleResources.Outputs.ListCollectionsFunctionArn
                                # - !GetAtt CollectionsModuleResources.Outputs.DeleteCollectionFunctionArn
                                # - !GetAtt PdfGenerationModuleResources.Outputs.GenerateDocsFunctionArn
                                # - !GetAtt ErrorExplanationModuleResources.Outputs.ExplainErrorFunctionArn

    SmartmanApi:
        Type: AWS::Serverless::Api
        Properties:
            StageName: Prod
            DefinitionBody:
                Fn::Transform:
                    Name: AWS::Include
                    Parameters:
                        Location: ./api/backend-api.yaml
            Cors:
                AllowMethods: "'GET,POST,DELETE,OPTIONS'"
                AllowHeaders: "'Content-Type,Authorization'"
                AllowOrigin: !Ref AllowedOrigin

    AuthModuleResources:
        Type: AWS::Serverless::Application
        Properties:
            Location: ./modules/auth/template.yaml
            Parameters:
                TableName: !Ref SmartmanTable
                SupabaseJwtSecret: !Ref SupabaseJwtSecret
                AllowedOrigin: !Ref AllowedOrigin

    # Placeholder for other modules (to be uncommented when implemented)
    # RequestModuleResources:
    #   Type: AWS::Serverless::Application
    #   Properties:
    #     Location: ./modules/request/template.yaml
    #     Parameters:
    #       TableName: !Ref SmartmanTable
    #       UpstashRedisUrl: !Ref UpstashRedisUrl
    #       SupabaseJwtSecret: !Ref SupabaseJwtSecret
    #       DeepSeekApiKey: !Ref DeepSeekApiKey
    #       AllowedOrigin: !Ref AllowedOrigin
    #
    # CollectionsModuleResources:
    #   Type: AWS::Serverless::Application
    #   Properties:
    #     Location: ./modules/collections/template.yaml
    #     Parameters:
    #       TableName: !Ref SmartmanTable
    #       SupabaseJwtSecret: !Ref SupabaseJwtSecret
    #       AllowedOrigin: !Ref AllowedOrigin
    #
    # PdfGenerationModuleResources:
    #   Type: AWS::Serverless::Application
    #   Properties:
    #     Location: ./modules/pdf-generation/template.yaml
    #     Parameters:
    #       TableName: !Ref SmartmanTable
    #       DocsBucket: !Ref DocsBucket
    #       AllowedOrigin: !Ref AllowedOrigin
    #
    # ErrorExplanationModuleResources:
    #   Type: AWS::Serverless::Application
    #   Properties:
    #     Location: ./modules/error-explanation/template.yaml
    #     Parameters:
    #       DeepSeekApiKey: !Ref DeepSeekApiKey
    #       AllowedOrigin: !Ref AllowedOrigin

Outputs:
    SmartmanApi:
        Description: URL of the API Gateway
        Value: !Sub 'https://${SmartmanApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
    GetProfileFunctionArn:
        Description: ARN of the GetProfile Lambda Function
        Value: !GetAtt AuthModuleResources.Outputs.GetProfileFunctionArn
    UpdateProfileFunctionArn:
        Description: ARN of the UpdateProfile Lambda Function
        Value: !GetAtt AuthModuleResources.Outputs.UpdateProfileFunctionArn
