AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Error Explanation Module for Smartman App (using DeepSeek)

Parameters:
    TableName:
        Type: String
    SupabaseJwtSecret:
        Type: String
    AllowedOrigin:
        Type: String
    DeepSeekApiKey:
        Type: String
        Description: DeepSeek API key
        NoEcho: true
    UpstashRedisRestUrl:
        Type: String
        Description: Upstash Redis REST API URL
        NoEcho: true
    UpstashRedisRestToken:
        Type: String
        Description: Upstash Redis REST API Token
        NoEcho: true

Globals:
    Function:
        Runtime: nodejs18.x
        Timeout: 30
        Environment:
            Variables:
                TABLE_NAME: !Ref TableName
                SUPABASE_JWT_SECRET: !Ref SupabaseJwtSecret
                ALLOWED_ORIGIN: !Ref AllowedOrigin
                DEEPSEEK_API_KEY: !Ref DeepSeekApiKey
                UPSTASH_REDIS_REST_URL: !Ref UpstashRedisRestUrl
                UPSTASH_REDIS_REST_TOKEN: !Ref UpstashRedisRestToken

Resources:
    ExplainErrorFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: src/explain-error/app.handler
            CodeUri: ./
            Policies:
                - DynamoDBReadPolicy:
                      TableName: !Ref TableName
            Runtime: nodejs18.x
        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2020'
                Sourcemap: false
                EntryPoints:
                    - src/explain-error/app.ts
                External:
                    - '@aws-sdk/client-dynamodb'
                    - '@aws-sdk/lib-dynamodb'

Outputs:
    ExplainErrorFunctionArn:
        Description: ARN of the ExplainError Lambda Function
        Value: !GetAtt ExplainErrorFunction.Arn
        Export:
            Name: !Sub '${AWS::StackName}-ExplainErrorFunctionArn'
