AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Request Module for Smartman App

Parameters:
    TableName:
        Type: String
    SupabaseJwtSecret:
        Type: String
    AllowedOrigin:
        Type: String
    UpstashRedisRestUrl:
        Type: String
        Description: Upstash Redis REST API URL
        NoEcho: true
    UpstashRedisRestToken:
        Type: String
        Description: Upstash Redis REST API Token
        NoEcho: true

Globals:
    Function:
        Runtime: nodejs18.x
        Timeout: 30
        Environment:
            Variables:
                TABLE_NAME: !Ref TableName
                SUPABASE_JWT_SECRET: !Ref SupabaseJwtSecret
                ALLOWED_ORIGIN: !Ref AllowedOrigin
                UPSTASH_REDIS_REST_URL: !Ref UpstashRedisRestUrl
                UPSTASH_REDIS_REST_TOKEN: !Ref UpstashRedisRestToken

Resources:
    ExecuteRequestFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: modules/request/src/execute-request/app.handler
            CodeUri: ../../
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: !Ref TableName
            Metadata:
                BuildMethod: esbuild
                BuildProperties:
                    Minify: true
                    Target: 'es2020'
                    Sourcemap: false
                    EntryPoints:
                        - modules/request/src/execute-request/app.ts
                    External:
                        - '@aws-sdk/client-dynamodb'
                        - '@aws-sdk/lib-dynamodb'
                        - jsonwebtoken
                        - node-fetch

Outputs:
    ExecuteRequestFunctionArn:
        Description: ARN of the ExecuteRequest Lambda Function
        Value: !GetAtt ExecuteRequestFunction.Arn
        Export:
            Name: !Sub '${AWS::StackName}-ExecuteRequestFunctionArn'
